src/main/java/br/com/library/model/Library.java
package br.com.library.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

@Entity
@Table(name="library")
public class Library implements Serializable{
	
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="libraryGenerator")
	@SequenceGenerator(name = "libraryGenerator", sequenceName = "SEQ_LIBRARY", allocationSize=1)
	private Integer id;
	
	@Column(length=50, nullable=false)
	private String nome;
	
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}
	
	@Override
	public String toString() {
		return "Library: "+ getId() + ", " + getNome();
	}

}

src/main/java/br/com/library/controllers/LibraryBean.java
package br.com.library.controllers;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

import br.com.library.dao.LibraryDao;
import br.com.library.model.Library;
import br.com.library.utils.FacesUtils;

@Controller
@Scope("request")
public class LibraryBean {
	
	private Library library;
	private List<Library> libraries;
	
	@Autowired
	private LibraryDao libraryDao;
	
	private FacesUtils facesUtils;
	
	@PostConstruct
	public void init(){
		library = new Library();
		libraries = new ArrayList<Library>();
		facesUtils = new FacesUtils();
		listaAll();
	}
	
	public Library getLibrary() {
		return library;
	}

	public void setLibrary(Library library) {
		this.library = library;
	}
	
	public List<Library> getLibraries() {
		return libraries;
	}

	public void setLibraries(List<Library> libraries) {
		this.libraries = libraries;
	}

	public void create(){
		libraryDao.insert(library);
		facesUtils.addSuccessMessage("Library successfully created");
	}
	
	public void save(){
		libraryDao.update(library);
		facesUtils.addSuccessMessage("Library successfully updated");
	}
	
	public void remove(Library library){
		libraryDao.remove(library);
		listaAll();
		facesUtils.addSuccessMessage("Library successfully deleted");
	}
	
	public void listaAll(){
		libraries = libraryDao.getAll();
		
	}
	
}

src/main/java/br/com/library/controllers/LivroBean.java
package br.com.library.controllers;

import javax.faces.bean.ManagedBean;

@ManagedBean
public class LivroBean {
	
	private String livroNome;
	
	public void livroDigitado(){
		System.out.println("Nome do livro eh " + livroNome);
	}

	public String getLivroNome() {
		return livroNome;
	}

	public void setLivroNome(String livroNome) {
		this.livroNome = livroNome;
	}
	
	
}

src/main/java/br/com/library/controllers/OlaMundoBean.java
package br.com.library.controllers;

import java.text.SimpleDateFormat;
import java.util.Date;

import javax.faces.bean.ManagedBean;

@ManagedBean
public class OlaMundoBean {

	private String nome = "gabiru";

	public String getHorario() {
		SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss");
		return "Atualizado em " + sdf.format(new Date());
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public void nomeFoiDigitado() {
		System.out.println("\nChamou o botão");
	}
}

WebContent/index.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html">

  <h:head>
    <title>Library</title>
  </h:head>
  <h:body>
    <h:outputText value ="Olá JSF!" />
    <br></br>
    <h:outputText value="#{olaMundoBean.horario}" />
    <br></br>
  	<h:form>
  		<h:inputText value="#{olaMundoBean.nome}"></h:inputText>
	    <br></br>
  		<h:commandButton value="Ok" action="#{olaMundoBean.nomeFoiDigitado}"></h:commandButton>
  	</h:form>
  
  </h:body>
</html>

WebContent/pages/library/cadastro.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	  xmlns:h="http://java.sun.com/jsf/html"
	  xmlns:f="http://java.sun.com/jsf/core">
<h:head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Create Library</title>
</h:head>
<h:body>
	<h:form>
		<h:messages />
		<h:panelGrid columns="2">
			<h:outputLabel value="Nome" for="nome" />
			<h:inputText id="nome" value="#{libraryBean.library.nome}" required="true" label="Nome"/>
			<h:commandButton value="Salvar" action="#{libraryBean.create}"/>
		</h:panelGrid>	
		<h:commandLink value="Back" action="lista" immediate="true" />
	</h:form>
</h:body>
</html>

WebContent/pages/library/edita.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	  xmlns:h="http://java.sun.com/jsf/html"
	  xmlns:f="http://java.sun.com/jsf/core"
	  xmlns:t="http://myfaces.apache.org/tomahawk">
<h:head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Update Library</title>
</h:head>
<h:body>
	<!-- matem o estado do objeto para edicao, util se existir campos read only para nao perder o valor do atributo -->
	<t:saveState value="#{libraryBean.library}" />
	<h:messages />
	
	<h:form>
		<h:inputHidden value="#{libraryBean.library.id}" />
		<h:panelGrid columns="2">
			<h:outputLabel value="Nome" for="nome" />
			<h:inputText id="nome" value="#{libraryBean.library.nome}" required="true">
				<f:validateLength minimum="5"/>
			</h:inputText>
			<h:commandButton value="Atualizar" action="#{libraryBean.save}"/>
		</h:panelGrid>	
		<h:commandLink value="Back" action="lista" immediate="true"/>
	</h:form>
</h:body>
</html>

WebContent/pages/library/lista.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	  xmlns:h="http://java.sun.com/jsf/html"
	  xmlns:f="http://java.sun.com/jsf/core"
	  xmlns:t="http://myfaces.apache.org/tomahawk">
<h:head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>All Libraries</title>
<h:outputStylesheet library="css" name="estilo.css"/>
</h:head>
<h:body>
	<!-- matem o estado do array -->
	<t:saveState value="#{libraryBean.libraries}"/>
	<h:form>
		<h:messages />
		<h:commandLink value="New" action="cadastro" />
		<h:dataTable value="#{libraryBean.libraries}" var="library">
			<h:column>
				<f:facet name="header">Id</f:facet>	
				#{library.id}
			</h:column>
			<h:column>
				<f:facet name="header">Nome</f:facet>	
				#{library.nome}
			</h:column>
			<h:column>
				<f:facet name="header"></f:facet>
				<h:commandLink value="delete" action="#{libraryBean.remove(library)}" />
			</h:column>
			<h:column>
				<f:facet name="header"></f:facet>
				<h:commandLink value="update" action="edita">
					<f:setPropertyActionListener value="#{library}" target="#{libraryBean.library}" />
				</h:commandLink>
			</h:column>
		</h:dataTable>
	</h:form>
</h:body>
</html>